AudioOutputDevice=alsa_output.usb-iBasso_iBasso-DC-Series-01.analog-stereo
EqualizerShowHandles=false
ExecutablePath=/usr/bin/jamesdsp
LastWindowGeometry=AdnQywADAAAAAAPFAAAAKQAAB3QAAAQsAAADxQAAACkAAAd0AAAELAAAAAAAAAAAB4AAAAPFAAAAKQAAB3QAAAQs
SendCrashReports=true
SetupDone=true
Theme=gtk2
ThemeColors=custom
ThemeColorsCustom=31,35,41;31,35,41;171,178,191;55,173,255;69,71,90
ThemeColorsCustomWhiteIcons=true
TrayIconMenu=passthrough;menu_preset;separator;show;quit;
