[install]

# whether to install optionalDependencies
optional = true

# whether to install devDependencies
dev = true

# whether to install devDependencies
peer = true

# equivalent to `--production` flag
production = false

# equivalent to `--dry-run` flag
dryRun = false

# set a username/password
# registry = "https://boydaihungst:password@registry.npmjs.org"

[install.lockfile]

# whether to save the lockfile to disk
save = true

# whether to save a non-Bun lockfile alongside bun.lockb
# only "yarn" is supported
print = "yarn"
