# NVIDIA drivers options
# See /usr/share/doc/nvidia-drivers-*/README.txt* for more information.

# nvidia-drivers and nouveau / nova cannot be used at same time.
# Comment out the following lines if you wish to allow either.
blacklist nouveau
blacklist nova_core

# By default, NVIDIA will handle the console/tty display and allow
# overriding DRM devices such as simpledrm. May or may not cause
# issues like being unable to display/switch tty properly or resume
# from sleep with *some* setups. Try disabling by uncommenting if
# need to troubleshoot issues, and re-enable if unrelated.
#options nvidia-drm fbdev=0
softdep nvidia post: nvidia-uvm nvidia-drm

# Suspend options. Notifiers=1 implies NVreg_PreserveVideoMemoryAllocations=1
# which is needed to avoid issues when resuming from suspend esp. on wayland
# (former systemd suspend services are not needed with kernel notifiers).
options nvidia \
  NVreg_UseKernelSuspendNotifiers=0 \
	NVreg_TemporaryFilePath=/var/tmp \
	NVreg_EnableS0ixPowerManagement=1 \
	NVreg_PreserveVideoMemoryAllocations=1

