-- local util = require "lspconfig.util"
-- local lsp_manager = require("lvim.lsp.manager")

-- local function get_typescript_server_path(root_dir)
--   local global_ts = os.getenv("HOME") .. "/.config/yarn/global/node_modules/typescript/lib/"
--   local found_ts = ""
--   local function check_dir(path)
--     found_ts = util.path.join(path, "node_modules", "typescript", "lib")
--     if util.path.exists(found_ts) then
--       return path
--     end
--   end
--   if util.search_ancestors(root_dir, check_dir) then
--     return found_ts
--   else
--     return global_ts
--   end
-- end
-- local function check_package_json_contain_vue_package(path)
--   local found_package_json = util.path.join(path, 'package.json')
--   if util.path.exists(found_package_json) then
--     local packageJson = vim.fn.json_decode(vim.fn.readfile(found_package_json))
--     if packageJson and packageJson.dependencies and (packageJson.dependencies.vue or packageJson.devDependencies.vue) then
--       return true
--     end
--   end
-- end
-- lsp_manager.setup("volar", {
--   filetypes = { "vue", "typescriptreact", "javascriptreact", "typescript", "javascript", "json" },
--   root_dir = function(fname)
--     return util.search_ancestors(fname, check_package_json_contain_vue_package)
--   end,
--   on_attach = function(client, bufnr)
--     local bufPath = vim.fn.expand('%:p')
--     local tsserverClients = vim.lsp.get_active_clients({ bufnr = bufnr, name = "tsserver" })
--     for _, tsserverClient in pairs(tsserverClients) do
--       if tsserverClient and not tsserverClient.is_stopped() and vim.lsp.buf_is_attached(bufnr, tsserverClient.id) and vim.lsp.buf_is_attached(bufnr, client.id) then
--         -- detach tsserver from attach to this buffer
--         if check_package_json_contain_vue_package(bufPath) then
--           vim.lsp.buf_detach_client(bufnr, tsserverClient.id)
--         else
--           vim.lsp.buf_detach_client(bufnr, client.id)
--           return
--         end
--       end
--     end
--     require("lvim.lsp").common_on_attach(client, bufnr)
--     client.server_capabilities.documentFormattingProvider = false
--     client.server_capabilities.documentRangeFormattingProvider = false
--   end,
--   on_new_config = function(new_config, new_root_dir)
--     new_config.init_options.typescript.tsdk = get_typescript_server_path(new_root_dir)
--   end,
-- })
