[sftp.home]
  host           = "home"
  # key_file       = "~/.ssh/id_ecdsa"
  key_passphrase = ""
  port           = 22
  user           = ""

[sftp.arm]
  host           = ""
  key_file       = "~/.ssh/id_ecdsa"
  key_passphrase = ""
  port           = 22
  user           = ""
