# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
  linemode       = "size"
  mouse_events   = ["click", "scroll", "drag", "touch", "move"]
  ratio          = [1, 3, 3]
  scrolloff      = 10
  show_hidden    = false
  show_symlink   = true
  sort_by        = "natural"
  sort_dir_first = true
  sort_fallback  = "alphabetical"
  sort_reverse   = false
  sort_sensitive = false
  sort_translit  = false

[preview]
  cache_dir       = "~/.cache/yazi/"
  image_delay     = 10
  image_filter    = "lanczos3"
  image_quality   = 75
  max_height      = 1600
  max_width       = 2560
  tab_size        = 2
  ueberzug_offset = [47, 12, 0, 0]
  ueberzug_scale  = 1.5
  wrap            = "yes"

[opener]
  bulk-rename = [{ run = "nvim %s", block = true }]

  mount_remote = [
    { run = 'clear && sudo mount -t nfs4 -o acl "home:/mnt/hdd" %s', block = true, desc = "Mount NFS server Ubuntu server home", for = "linux" },
    { run = "sshfs huyhoang@home:/mnt/hdd %s", desc = "Mount SSHFS server Ubuntu server home", orphan = true, for = "linux" },
    { run = "clear && sudo umount %s", block = true, desc = "Unmount", for = "linux" },
  ]

  # https://github.com/boydaihungst/subtitle-signs-transfer
  # https://github.com/boydaihungst/crunchyroll-sub-downloader
  subtitle_editor_ass       = [
    { run = "gtk-launch aegisub %s1", desc = "Aegisub", orphan = true, for = "linux" },
    { run = 'clear && $HOME/git/subtitle-signs-transfer/.venv/bin/python $HOME/git/subtitle-signs-transfer/main.py %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Transfer signs", for = "linux" },
    { run = "clear && $HOME/git/crunchy-subs/.venv/bin/python $HOME/git/crunchy-subs/subtitle_processor.py %s", orphan = true, desc = "Subtitle: Clean", for = "linux" },
    { run = 'clear && assfonts -i %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Embed fonts", for = "linux" },
    { run = 'clear && $HOME/git/scripts/vtt-srt-to-ass.sh %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Convert to ASS", for = "linux" },
  ]
  subtitle_editor_srt       = [
    { run = "gtk-launch aegisub %s1", desc = "Aegisub", orphan = true, for = "linux" },
    { run = 'clear && $HOME/git/scripts/vtt-srt-to-ass.sh %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Convert to ASS", for = "linux" },
  ]
  subtitle_editor_vtt       = [
    { run = 'clear && $HOME/git/scripts/vtt-srt-to-ass.sh %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Convert to ASS", for = "linux" },
  ]
  subtitle_processor_folder = [
    { run = "clear && $HOME/git/scripts/extract_sub.sh %s", orphan = true, desc = "Subtitle: Extract", for = "linux" },
    { run = 'clear && $HOME/git/subtitle-signs-transfer/.venv/bin/python $HOME/git/subtitle-signs-transfer/main.py %s; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Transfer signs", for = "linux" },
    { run = "clear && $HOME/git/crunchy-subs/.venv/bin/python $HOME/git/crunchy-subs/subtitle_processor.py %s", orphan = true, desc = "Subtitle: Clean", for = "linux" },
    { run = 'kitty -- "$HOME/git/OCR/batch.sh" %s', orphan = true, desc = "Subtitle: OCR", for = "linux" },
    # { run = 'wezterm start -- "$HOME/git/OCR/batch.sh" %s', orphan = true, desc = "Subtitle: OCR", for = "linux" },
    { run = 'clear && assfonts -i %s1/*.ass; read -rp "Press Enter to exit..."', block = true, desc = "Subtitle: Embed fonts", for = "linux" },
  ]

  torrent_editor = [
    { run = "torrent-file-editor %s1", desc = "Torrent file editor", orphan = true, for = "linux" },
  ]

  manpage = [
    { run = "man %s1", orphan = true, desc = "Manpage", for = "linux" }
  ]

  wine = [{ run = "wine64 %s1", orphan = true, desc = "Wine64", for = "linux" }]

  audio = [
    { run = "mpc --host $HOME/.config/mpd/socket clear && mpc --host $HOME/.config/mpd/socket add %s && mpc play", orphan = true, desc = "Play audio via mpd", for = "linux" }
  ]

  video = [
    { run = "killall mpv; mpv %s", orphan = true, desc = "Mpv", for = "linux" },
    { run = "$HOME/git/scripts/extract_sub.sh %s", orphan = true, desc = "Extract subtitle", for = "linux" },
    # { run = "smplayer %s", orphan = true, desc = "Smplayer", for = "linux" },
    # { run = "ya emit escape select && ya emit visual_mode && ya emit plugin simple-tag 'add-tag --key=`' && ya emit escape select && smplayer %s", orphan = true, desc = "Smplayer", for = "linux" },
    { run = "vlc %s", orphan = true, desc = "Vlc", for = "linux" },
  ]

  document = [
    { run = "libreoffice %s", orphan = true, desc = "Libreoffice", for = "linux" },
  ]

  ebook_viewer = [
    { run = "ebook-viewer %s", orphan = true, desc = "Ebook-viewer", for = "linux" },
    { run = "calibre %s", orphan = true, desc = "Calibre", for = "linux" },
  ]
  image        = [
    { run = "gthumb %s", orphan = true, desc = "Gthumb", for = "linux" },
    { run = "gimp %s", orphan = true, desc = "Gimp", for = "linux" },
    { run = "inkscape %s", orphan = true, desc = "Inkscape", for = "linux" },
    { run = "cp %s1 $HOME/.config/hypr/wallpaper && killall hyprpaper && hyprctl eval 'hl.exec_cmd(\"hyprpaper\")'", orphan = false, block = false, desc = "Set as wallpaper (hyprland)", for = "linux" },
  ]

  terminal = [
    { run = "kitty %s1", orphan = true, desc = "Kitty", for = "linux" },
    # { run = 'wezterm start --cwd %s1', orphan = true, desc = "Wezterm", for = "linux" },
  ]

  lazygit = [
    { run = 'kitty --app-id "lazygit" -- ~/.config/yazi/lazygit.sh %s1', orphan = true, desc = "Lazygit", for = "linux" },
  ]

  edit = [
    { run = 'kitty --app-id "nvim" -- nvim %s', orphan = true, desc = "Nvim", for = "linux" },
    # { run = 'wezterm start --class "nvim" -- nvim %s', orphan = true, desc = "Nvim", for = "linux" },
    { run = "xed %s", desc = "Xed", orphan = true, for = "linux" },
  ]

  open = [
    { run = "xdg-open %s1", desc = "Xdg-open", orphan = true, for = "linux" },
  ]

  reveal = [
    { run = 'xdg-open "$(dirname %s1)"', desc = "Reveal", for = "linux" },
    { run = "open -R %s1", desc = "Reveal", for = "macos" },
    { run = "explorer /select,%1", orphan = true, desc = "Reveal", for = "windows" },
    { run = '''exiftool %s1; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
  ]

  execute = [{ run = "%s1", desc = "Run", for = "linux" }]

  archive  = [
    { run = "ya pub extract --list %s", desc = "Extract here", for = "unix" },
    { run = "ya pub extract --list %*", desc = "Extract here", for = "windows" },
    { run = "file-roller %s", orphan = true, desc = "File-roller", for = "linux" },
    { run = "7zFM %s", orphan = true, desc = "7z GUI", for = "linux" },
  ]
  download = [
    { run = "ya emit download --open %S", desc = "Download and open" },
    { run = "ya emit download %S", desc = "Download" },
  ]
  trash    = [
    { run = "ya pub trash-restore --list %S", desc = "Restore selected files" },
    { run = "ya pub trash-empty --list %S", desc = "Empty trash bin" },
  ]

[open]
  rules = [
    # Trash
    { mime = "trash/**", use = ["open", "trash"] },
    { mime = "image/xcursor", use = ["edit"] },
    { mime = "application/mbox", use = ["edit"] },
    { mime = "text/shellscript", use = ["execute", "edit"] },
    { url = "bulk-rename.txt", use = ["bulk-rename"], block = true },
    # Folder
    { url = "/mnt/remote/", use = ["mount_remote", "terminal"] },
    { url = "*/", use = ["terminal", "lazygit", "subtitle_processor_folder"] },

    # subtitle
    { url = "*.ass", use = ["edit", "subtitle_editor_ass"] },
    { url = "*.srt", use = ["edit", "subtitle_editor_srt"] },
    { url = "*.vtt", use = ["edit", "subtitle_editor_vtt"] },
    # Virtual file system
    { mime = "vfs/{absent,stale}", use = "download" },

    # Torrent files
    { url = "*.{torrent}", use = ["torrent_editor", "edit"] },

    # html
    { url = "*.{html,htm,xhtml,xhtm,shtml}", use = ["open", "edit"] },

    # manpage
    { url = "*.1", use = ["manpage"] },
    # wine64
    { url = "*.{exe,msi}", use = ["wine"] },

    # Audio
    { mime = "audio/*", use = ["audio"] },
    { mime = "*/ogg", use = ["audio"] },

    # Video
    { mime = "video/*", use = ["video"] },
    # Document
    { url = "*.pdf", use = ["open"] },
    { url = "*.{pttx,ptt,odd,odf,odg,odp,ods,odt,doc,docx,sxc,xls,xlsx,xtl,gnm,gnumeric,csv}", use = [
      "open",
      "document"
    ] },
    { url = "*.{azw,cbc,cbr,cbz,epub,fb2,htm,html,lit,lrf,mobi,opf,rb,pdb,pdf,pml,pmlz,prc,recipe,rtf,shtm,shtml,tcr}", use = [
      "ebook-viewer"
    ] },
    # Text
    { mime = "text/*", use = ["edit"] },

    # Image
    { mime = "image/*", use = ["image"] },
    { url = "*.xcf", use = ["image"] },
    { mime = "application/gentoo.ebuild", use = ["edit"] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
      "archive"
    ] },

    # JSON
    { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = [
      "edit"
    ] },

    # Empty file
    { mime = "inode/empty", use = ["edit"] },
    { mime = "application/{executable,pie-executable}", use = [
      "execute",
      "edit"
    ] },

    # Fallback
    { url = "*", use = ["open", "edit"] },
  ]

[tasks]
  bizarre_retry    = 5
  fetch_workers    = 5
  file_workers     = 3
  image_alloc      = 1073741824      # 1024MB
  image_bound      = [10000, 10000]
  plugin_workers   = 5
  preload_workers  = 2
  process_workers  = 5
  suppress_preload = false

[plugin]
  fetchers   = [
    # Mimetype
    # { id = "mime", url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*", run = "mime-ext.local", prio = "high" },
    # { id = "mime", url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*/", run = "mime.dir", prio = "high" },
    { url = "*/", run = "mime.dir", prio = "high", group = "mime" },
    { url = "local://*", run = "mime-ext.local", prio = "high", group = "mime" },
    { url = "trash://*", run = "mime.trash", prio = "high", group = "mime" },
    { url = "remote://*", run = "mime-ext.remote", prio = "high", group = "mime" },
    { url = "*", run = "simple-tag", group = "simple-tag" },
    { url = "*/", run = "simple-tag", group = "simple-tag" },
  ]
  preloaders = [
    { url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*", run = "noop", prio = "high" },
    { url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*/", run = "noop", prio = "high" },
    # Do not preload these paths
    { url = "/mnt/**/*", run = "noop", prio = "high" },
    { url = "/home/huyhoang/Media/**/*", run = "noop", prio = "high" },
    # Audio + Video + Image
    { url = "*.{ai,eps,ait}", run = "mediainfo" },
    # { mime = "{audio,video,image}/*", run = "mediainfo" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Font
    { mime = "{font/*,application/ms-opentype}", run = "better-font" },

    # Trash
    { mime = "trash/**", run = "trash" },
  ]

  spotters = [
    # Multi-file
    { mime = "multi/*", run = "multi" },

    # Trash
    { mime = "trash/**", run = "trash" },
    # Folder
    { url = "*/", run = "folder" },
    { url = "/mnt/**/*", run = "file-extra-metadata", prio = "high" },
    # Code
    # { mime = "text/*", run = "code" },
    # { mime = "application/{mbox,javascript,wine-extension-ini,apple.mpegurl}", run = "code" },
    # Image
    { mime = "image/xcursor", run = "file-extra-metadata" },
    { mime = "image/svg+xml", run = "svg" },
    { mime = "image/{avif,hei?,jxl}", run = "magick" },
    { mime = "image/*", run = "image" },
    # Video
    { mime = "video/*", run = "video" },
    # Virtual file system
    { mime = "vfs/*", run = "vfs" },
    # Error
    { mime = "null/*", run = "null" },
    # Fallback
    # { url = "*", run = "file" },
    { url = "*", run = "file-extra-metadata" },
  ]

  previewers = [
    { url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*", run = "noop", prio = "high" },
    { url = "/run/user/*/gvfs/google-drive:host=gmail.com,user=*/**/*/", run = "noop", prio = "high" },
    { url = "*/", run = "smart-truncate" },
    # { url = "*/", run = "folder" },
    # Do not preview these paths
    # { url = "/home/huyhoang/Media/**/*", run = "noop" },
    # Markdown
    # { mime = "text/plain", run = 'custom-code' },
    { mime = "text/markdown", run = 'enhance-piper --cache-max-lines=1000000 --cache-limit=1000 -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    # Code
    { mime = "text/*", run = 'enhance-piper  --cache-max-lines=1000000 --cache-limit=1000 -- bat -p --color=always --theme=base16 "$1"' },
    # Torrent
    { mime = "application/bittorrent", run = 'enhance-piper -- transmission-show "$1" --no-header | CLICOLOR_FORCE=1 glow -w=$w -s=dark -' },
    # Do not preview these paths except text file

    { mime = "application/{mbox,javascript,wine-extension-ini,subrip,apple.mpegurl,xml,xhtml+xml,gentoo.ebuild}", run = 'enhance-piper -- bat -p --color=always --theme=base16 "$1"' },
    { url = "/mnt/**/*", run = "noop" },
    # Xresources linux
    { mime = "image/xcursor", run = 'enhance-piper -- bat -p --color=always --theme=base16 "$1"' },
    # JSON
    # Audio + Video + Image
    { url = "*.{ai,eps,ait}", run = "mediainfo" },
    { mime = "{video,image,audio}/*", run = "mediainfo" },
    { mime = "application/{json,ndjson}", run = "json" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "archive" },
    { mime = "application/{debian-package,redhat-package-manager,rpm}", run = "archive" },
    { mime = "application/debian.binary-package", run = "archive" },
    { mime = "application/android.package-archive", run = "archive" },
    { url = "*.{AppImage,appimage}", run = "archive" },
    # Virtual Disk / Disk Image
    { mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}", run = "archive" },
    { mime = "application/virtualbox-{vhd,vhdx}", run = "archive" },
    { url = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}", run = "archive" },
    # Font
    { mime = "{font/*,application/ms-opentype}", run = "better-font" },
    # Empty file
    { mime = "inode/empty", run = "empty" },
    # Virtual file system
    { mime = "vfs/*", run = "vfs" },
    # Trash
    { mime = "trash/**", run = "trash" },
    # Error
    { mime = "null/*", run = "null" },
    # Fallback
    # { url = "*", run = "file" },
    { url = "*", run = "file-extra-metadata" },
  ]

[input]
  cursor_blink = false

  # cd
  cd_offset = [0, 0, 50, 3]
  cd_origin = "center"
  cd_title  = "Change directory:"

  # create
  create_offset = [0, 0, 50, 3]
  create_origin = "center"
  create_title  = ["Create:", "Create (dir):"]

  # rename
  rename_offset = [0, 1, 50, 3]
  rename_origin = "hovered"
  rename_title  = "Rename:"

  # filter
  filter_offset = [0, 0, 50, 3]
  filter_origin = "center"
  filter_title  = "Filter:"

  # find
  find_offset = [0, 0, 50, 3]
  find_origin = "center"
  find_title  = ["Find next:", "Find previous:"]

  # search
  search_offset = [0, 0, 50, 3]
  search_origin = "center"
  search_title  = "Search via {n}:"

  # shell
  shell_offset = [0, 0, 50, 3]
  shell_origin = "center"
  shell_title  = ["Shell:", "Shell (block):"]

[confirm]
  # trash
  trash_offset = [0, 0, 70, 40]
  trash_origin = "center"
  trash_title  = "Trash {n} selected file{s}?"

  # delete
  delete_offset = [0, 0, 70, 40]
  delete_origin = "center"
  delete_title  = "Permanently delete {n} selected file{s}?"

  # overwrite
  overwrite_body   = "Will overwrite the following file:"
  overwrite_offset = [0, 0, 50, 40]
  overwrite_origin = "center"
  overwrite_title  = "Overwrite file?"

  # quit
  quit_body   = "The following task is still running, are you sure you want to quit?"
  quit_offset = [0, 0, 50, 15]
  quit_origin = "center"
  quit_title  = "Quit?"

[pick]
  open_offset = [0, 1, 50, 7]
  open_origin = "hovered"
  open_title  = "Open with:"

[which]
  sort_by        = "desc"
  sort_reverse   = false
  sort_sensitive = false
  sort_translit  = false
