options nvidia_drm modeset=1
# Disable VRAM preservation and set a temporary file path for suspend/hibernate
options nvidia NVreg_PreserveVideoMemoryAllocations=0 NVreg_TemporaryFilePath=/var/tmp

# Enable NVIDIA's own power management services
options nvidia NVreg_EnableGpuFirmware=0
