# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
splash = false
wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/wallpaper
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/.config/hypr/wallpaper
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = ~/.config/hypr/wallpaper
  fit_mode = cover
}
