general {
    lock_cmd = pidof hyprlock || hyprlock -q --no-fade-in       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({action = \"enable\"})" && ddcutil --sn="AWBS39A000221" setvcp d6 1 && /home/huyhoang/git/Monitor_Mode_AOC/monitor_mode -l 80  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}
listener {
    timeout = 150
    on-timeout = /home/huyhoang/git/Monitor_Mode_AOC/monitor_mode -l 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = /home/huyhoang/git/Monitor_Mode_AOC/monitor_mode -l 80                 # monitor backlight restore.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener {
    timeout = 150
    on-timeout = brightnessctl -sd platform::kbd_backlight set 0 # turn off keyboard backlight.
    on-resume = brightnessctl -rd platform::kbd_backlight        # turn on keyboard backlight.
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch "hl.dsp.dpms({action = \"disable\"})"         # screen off when timeout has passed
    on-resume = hyprctl dispatch "hl.dsp.dpms({action = \"enable\"})" && brightnessctl -r           # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 360
    on-timeout = ddcutil --sn="AWBS39A000221" setvcp d6 4
    on-resume = ddcutil --sn="AWBS39A000221" setvcp d6 1 && /home/huyhoang/git/Monitor_Mode_AOC/monitor_mode -l 80
}

listener {
    timeout = 1800
    on-timeout = loginctl suspend # suspend pc
}
