# archbuild
# Autogenerated from man page /usr/share/man/man1/archbuild.1.gz
complete -c archbuild -s h -d 'Output command line options'
complete -c archbuild -s c -d 'Recreate the chroot before building'
complete -c archbuild -s r -d 'Create chroots in this directory'

