# arch-nspawn
# Autogenerated from man page /usr/share/man/man1/arch-nspawn.1.gz
complete -c arch-nspawn -s C -d 'Location of a pacman config file'
complete -c arch-nspawn -s M -d 'Location of a makepkg config file'
complete -c arch-nspawn -s c -d 'Set pacman cache, if no directory is specified the passed pacman'
complete -c arch-nspawn -s f -d 'Copy file from the host to the chroot'
complete -c arch-nspawn -s s -d 'Do not run setarch'
complete -c arch-nspawn -s h -d 'Show this usage message'

