# checkpkg
# Autogenerated from man page /usr/share/man/man1/checkpkg.1.gz
complete -c checkpkg -s r -l rmdir -d 'Remove the temporary directory created to contain the file and library list o…'
complete -c checkpkg -s w -l warn -d 'Print a warning instead of a regular message in case of soname differences'
complete -c checkpkg -s M -l makepkg-config -d 'Set an alternate makepkg configuration file'
complete -c checkpkg -s h -l help -d 'Show a help text'

