# clambc
# Autogenerated from man page /usr/share/man/man1/clambc.1.gz
complete -c clambc -l help -s h -d 'Show help'
complete -c clambc -l version -s V -d 'Show version'
complete -c clambc -l debug -d 'Show debug'
complete -c clambc -l force-interpreter -s f -d 'Force using the interpreter instead of the JIT'
complete -c clambc -l trust-bytecode -s t -d 'Trust loaded bytecode (default yes)'
complete -c clambc -l info -s i -d 'Print information about bytecode'
complete -c clambc -l printsrc -s p -d 'Print bytecode source'
complete -c clambc -l printbcir -s c -d 'Print IR of bytecode signature'
complete -c clambc -l input -s r -d 'Input file to run the bytecode on'
complete -c clambc -l trace -s T -d 'Set bytecode trace level 0. 7 (default 7)'
complete -c clambc -l no-trace-showsource -d 'Don\'t show source line during tracing'
complete -c clambc -l statistics -d 'Collect and print bytecode execution statistics'

