# clamdtop
# Autogenerated from man page /usr/share/man/man1/clamdtop.1.gz
complete -c clamdtop -s h -l help -d 'Display help information and exit'
complete -c clamdtop -s V -l version -d 'Print version number and exit'
complete -c clamdtop -l config-file -d 'Read clamd settings from FILE, to determine how to connect to it'

