# clamonacc
# Autogenerated from man page /usr/share/man/man8/clamonacc.8.gz
complete -c clamonacc -s h -l help -d 'Output help information and exit'
complete -c clamonacc -s V -l version -d 'Print the version number and exit'
complete -c clamonacc -s v -l verbose -d 'Be verbose'
complete -c clamonacc -s l -l log -d 'Save the scan report to FILE'
complete -c clamonacc -s F -l foreground -d 'Run in foreground; do not daemonize'
complete -c clamonacc -s W -l watch-list -d 'Watch directories from FILE'
complete -c clamonacc -s e -l exclude-list -d 'Exclude directories from FILE'
complete -c clamonacc -s p -l ping -d 'Ping clamd up to [A] times at optional interval [I] until it responds'
complete -c clamonacc -s w -l wait -d 'Wait up to 30 seconds for clamd to start'
complete -c clamonacc -l remove -d 'Remove infected files.  Be careful'
complete -c clamonacc -l move -d 'Move infected files into DIRECTORY'
complete -c clamonacc -l copy -d 'Copy infected files into DIRECTORY'
complete -c clamonacc -s c -l config-file -d 'Read configuration from FILE'
complete -c clamonacc -l allmatch -d 'Continue scanning within file after finding a match'
complete -c clamonacc -l fdpass -d 'Pass the file descriptor permissions to clamd'

