# clamav-milter
# Autogenerated from man page /usr/share/man/man8/clamav-milter.8.gz
complete -c clamav-milter -s h -l help -d 'Output help information and exit'
complete -c clamav-milter -s V -l version -d 'Print the version number and exit'

