# clamconf
# Autogenerated from man page /usr/share/man/man1/clamconf.1.gz
complete -c clamconf -s h -l help -d 'Display help and exit'
complete -c clamconf -s V -l version -d 'Display software version and exit'
complete -c clamconf -s c -l config-dir -d 'Search for configuration files clamd. conf and freshclam. conf in DIR'
complete -c clamconf -s n -l non-default -d 'Only print non-default settings'

