# clamsubmit
# Autogenerated from man page /usr/share/man/man1/clamsubmit.1.gz
complete -c clamsubmit -s h -s '?' -d 'Display help to stderr and exit'
complete -c clamsubmit -s e -d 'Required option for setting the email address for the submission'
complete -c clamsubmit -s n -d 'Submit a file that reports as a false negative (ClamAV reports CLEAN)'
complete -c clamsubmit -s N -d 'Required option for setting the name of the sender for the submission'
complete -c clamsubmit -s p -d 'Submit a file that reports as a false positive (ClamAV flags the file as viru…'

