# clamd
# Autogenerated from man page /usr/share/man/man8/clamd.8.gz
complete -c clamd -s h -l help -d 'Output help information and exit'
complete -c clamd -s V -l version -d 'Print the version number and exit'
complete -c clamd -s F -l foreground -d 'Run in foreground; do not daemonize'
complete -c clamd -l debug -d 'Enable debug mode'
complete -c clamd -s c -l config-file -d 'Read configuration from FILE'
complete -c clamd -l fail-if-cvd-older-than -d 'Return with a nonzero error code if the virus database is older than the spec…'
complete -c clamd -l datadir -d 'Load signatures from DIRECTORY'

