# cmark
# Autogenerated from man page /usr/share/man/man1/cmark.1.gz
complete -c cmark -l to -s t -d 'Specify output format (html, man, xml, latex, commonmark)'
complete -c cmark -l width -d 'Specify a column width to which to wrap the output'
complete -c cmark -l hardbreaks -d 'Render soft breaks (newlines inside paragraphs in the CommonMark source) as h…'
complete -c cmark -l nobreaks -d 'Render soft breaks as spaces'
complete -c cmark -l sourcepos -d 'Include source position attribute'
complete -c cmark -l validate-utf8 -d 'Validate UTF-8, replacing illegal sequences with U+FFFD'
complete -c cmark -l smart -d 'Use smart punctuation'
complete -c cmark -l - -d ' will be rendered as ellipses'
complete -c cmark -l safe -d 'Omit raw HTML and potentially dangerous URLs (default)'
complete -c cmark -l unsafe -d 'Render raw HTML or potentially dangerous URLs, overriding the default (--safe…'
complete -c cmark -l help -d 'Print usage information'
complete -c cmark -l version -d 'Print version'

