# crunchy-cli-search
# Autogenerated from man page /usr/share/man/man1/crunchy-cli-search.1.gz
complete -c crunchy-cli-search -l audio -d 'Audio languages to include'
complete -c crunchy-cli-search -l search-top-results-limit -d 'Limit of search top search results'
complete -c crunchy-cli-search -l search-series-limit -d 'Limit of search series results'
complete -c crunchy-cli-search -l search-movie-listing-limit -d 'Limit of search movie listing results'
complete -c crunchy-cli-search -l search-episode-limit -d 'Limit of search episode results'
complete -c crunchy-cli-search -l search-music-limit -d 'Limit of search music results'
complete -c crunchy-cli-search -s o -l output -d 'Format of the output text'
complete -c crunchy-cli-search -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

