# crunchy-cli-download
# Autogenerated from man page /usr/share/man/man1/crunchy-cli-download.1.gz
complete -c crunchy-cli-download -s a -l audio -d 'Audio language.  Can only be used if the provided url(s) point to a series'
complete -c crunchy-cli-download -s s -l subtitle -d 'Subtitle language'
complete -c crunchy-cli-download -s o -l output -d 'Name of the output file'
complete -c crunchy-cli-download -l output-specials -d 'Name of the output file if the episode is a special'
complete -c crunchy-cli-download -l universal-output -d 'Sanitize the output file for use with all operating systems'
complete -c crunchy-cli-download -s r -l resolution -d 'The video resolution.  Can either be specified via the pixels (e. g'
complete -c crunchy-cli-download -l language-tagging -d 'Specified which language tagging the audio and subtitle tracks and language s…'
complete -c crunchy-cli-download -l ffmpeg-preset -d 'Presets for converting the video to a specific coding format'
complete -c crunchy-cli-download -l ffmpeg-threads -d 'The number of threads used by ffmpeg to generate the output file'
complete -c crunchy-cli-download -l skip-existing -d 'Skip files which are already existing by their name'
complete -c crunchy-cli-download -l skip-specials -d 'Skip special episodes'
complete -c crunchy-cli-download -l include-chapters -d 'Includes chapters (e. g.  intro, credits, . )'
complete -c crunchy-cli-download -s y -l yes -d 'Skip any interactive input'
complete -c crunchy-cli-download -l force-hardsub -d 'Force subtitles to be always burnt-in'
complete -c crunchy-cli-download -s t -l threads -d 'The number of threads used to download'
complete -c crunchy-cli-download -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'

