# crunchy-cli-login
# Autogenerated from man page /usr/share/man/man1/crunchy-cli-login.1.gz
complete -c crunchy-cli-login -l remove -d 'Remove your stored credentials (instead of saving them)'
complete -c crunchy-cli-login -s h -l help -d 'Print help'

