# crunchy-cli
# Autogenerated from man page /usr/share/man/man1/crunchy-cli.1.gz
complete -c crunchy-cli -s v -l verbose -d 'Verbose output'
complete -c crunchy-cli -s q -l quiet -d 'Quiet output.  Does not print anything unless it\\*(Aqs a error'
complete -c crunchy-cli -l lang -d 'Overwrite the language in which results are returned'
complete -c crunchy-cli -l experimental-fixes -d 'Enable experimental fixes which may resolve some unexpected errors'
complete -c crunchy-cli -l credentials -d 'Login with credentials (email and password)'
complete -c crunchy-cli -l etp-rt -d 'Login with the etp-rt cookie'
complete -c crunchy-cli -l anonymous -d 'Login anonymously / without an account'
complete -c crunchy-cli -l proxy -d 'Use a proxy to route all traffic through'
complete -c crunchy-cli -l user-agent -d 'Use custom user agent'
complete -c crunchy-cli -l speed-limit -d 'Maximal speed to download/request (may be a bit off here and there)'
complete -c crunchy-cli -s h -l help -d 'Print help (see a summary with \\*(Aq-h\\*(Aq)'
complete -c crunchy-cli -s V -l version -d 'Print version SUBCOMMANDS'

