# diffpkg
# Autogenerated from man page /usr/share/man/man1/diffpkg.1.gz
complete -c diffpkg -s M -l makepkg-config -d 'Set an alternate makepkg configuration file'
complete -c diffpkg -s P -l pool -d 'Search diff target in pool dir (default \\*(Aq/srv/ftp/pool\\*(Aq)'
complete -c diffpkg -s v -l verbose -d 'Provide more detailed/unfiltered output'
complete -c diffpkg -s h -l help -d 'Show a help text'
complete -c diffpkg -l color
complete -c diffpkg -s u -s U -l unified
complete -c diffpkg -s y -l side-by-side
complete -c diffpkg -s W -l width
complete -c diffpkg -s l -l list
complete -c diffpkg -s d -l diffoscope
complete -c diffpkg -s p -l pkginfo
complete -c diffpkg -s b -l buildinfo

