# gh-auth-switch
# Autogenerated from man page /usr/share/man/man1/gh-auth-switch.1.gz
complete -c gh-auth-switch -s h -l hostname -d 'The hostname of the GitHub instance to switch account for'
complete -c gh-auth-switch -s u -l user -d 'The account to switch to EXAMPLE'

