# libiconv
# Autogenerated from man page /usr/share/man/man1/libiconv.1.gz
complete -c libiconv -s f -l from-code -d 'Specifies the encoding of the input'
complete -c libiconv -s t -l to-code -d 'Specifies the encoding of the output'
complete -c libiconv -s c -d 'When this option is given, characters that cannot be converted are silently d…'
complete -c libiconv -l unicode-subst -d 'When this option is given, Unicode characters that cannot be represented in t…'
complete -c libiconv -l byte-subst -d 'When this option is given, bytes in the input that are not valid in the sourc…'
complete -c libiconv -l widechar-subst -d 'When this option is given, wide characters in the input that are not valid in…'
complete -c libiconv -s s -l silent -d 'When this option is given, error messages about invalid or unconvertible char…'

