# makerepropkg
# Autogenerated from man page /usr/share/man/man1/makerepropkg.1.gz
complete -c makerepropkg -s d -d 'If packages are not reproducible, compare them using diffoscope'
complete -c makerepropkg -s n -d 'Do not run the check() function in the PKGBUILD'
complete -c makerepropkg -s c -d 'Set the pacman cache directory'
complete -c makerepropkg -s M -d 'Location of a makepkg config file'
complete -c makerepropkg -s l -d 'The directory name to use as the chroot namespace Useful for maintaining mult…'
complete -c makerepropkg -s h -d 'Show this usage message'

