# makechrootpkg
# Autogenerated from man page /usr/share/man/man1/makechrootpkg.1.gz
complete -c makechrootpkg -s h -d 'Show this usage message'
complete -c makechrootpkg -s c -d 'Clean the chroot before building'
complete -c makechrootpkg -s d -d 'Bind directory into build chroot as read-write'
complete -c makechrootpkg -s D -d 'Bind directory into build chroot as read-only'
complete -c makechrootpkg -s u -d 'Update the working copy of the chroot before building This is useful for rebu…'
complete -c makechrootpkg -s r -d 'The chroot dir to use'
complete -c makechrootpkg -s I -d 'Install a package into the working copy of the chroot'
complete -c makechrootpkg -s l -d 'The directory to use as the working copy of the chroot Useful for maintaining…'
complete -c makechrootpkg -s n -d 'Run namcap on the build package'
complete -c makechrootpkg -s C -d 'Run checkpkg on the build package'
complete -c makechrootpkg -s T -d 'Build in a temporary directory'
complete -c makechrootpkg -s U -d 'Run makepkg as a specified user'
complete -c makechrootpkg -s x -d 'Inspect chroot after build, possible modes are never (default), always or fai…'

