# mkarchroot
# Autogenerated from man page /usr/share/man/man1/mkarchroot.1.gz
complete -c mkarchroot -s U -d 'Use pacman -U to install packages'
complete -c mkarchroot -s C -d 'Location of a pacman config file'
complete -c mkarchroot -s M -d 'Location of a makepkg config file'
complete -c mkarchroot -s c -d 'Set pacman cache'
complete -c mkarchroot -s f -d 'Copy file from the host to the chroot'
complete -c mkarchroot -s s -d 'Do not run setarch'
complete -c mkarchroot -s h -d 'Output command line options'

