# mkvtoolnix-gui
# Autogenerated from man page /usr/share/man/man1/mkvtoolnix-gui.1.gz
complete -c mkvtoolnix-gui -l merge
complete -c mkvtoolnix-gui -l info
complete -c mkvtoolnix-gui -l edit-chapters -d or
complete -c mkvtoolnix-gui -l edit-headers
complete -c mkvtoolnix-gui -s h -l help
complete -c mkvtoolnix-gui -s V -l version

