# newrole
# Autogenerated from man page /usr/share/man/man1/newrole.1.gz
complete -c newrole -s r -d or
complete -c newrole -l role -d 'option is specified, then the new context will have the role specified by ROLE'
complete -c newrole -s t -d or
complete -c newrole -l type -d 'option is specified, then the new context will have the type (domain) specifi…'
complete -c newrole -s l -d or
complete -c newrole -l level -d 'option is specified, then the new context will have the sensitivity level spe…'
complete -c newrole -s p -d or
complete -c newrole -l preserve-environment -d 'option is specified, the shell with the new SELinux context will preserve env…'
complete -c newrole -s V -d 'or '
complete -c newrole -l version -d 'shows the current version of newrole'

