# offload-build
# Autogenerated from man page /usr/share/man/man1/offload-build.1.gz
complete -c offload-build -s r -l repo -d 'Build against a specific repository'
complete -c offload-build -s a -l arch -d 'Build against a specific architecture'
complete -c offload-build -s s -l server -d 'Offload to a specific build server.  The default is build. archlinux'
complete -c offload-build -s h -l help -d 'Show a help text'

