# pg_waldump
# Autogenerated from man page /usr/share/man/man1/pg_waldump.1.gz
complete -c pg_waldump -o 'b
.br
--bkp-details' -d 'Output detailed information about backup blocks'
complete -c pg_waldump -s B -d 'Only display records that modify the given block'
complete -c pg_waldump -s e -d 'Stop reading at the specified WAL location, instead of reading to the end of …'
complete -c pg_waldump -o 'f
.br
--follow' -d 'After reaching the end of valid WAL, keep polling once per second for new WAL…'
complete -c pg_waldump -s F -d 'If provided, only display records that modify blocks in the given fork'
complete -c pg_waldump -s n -d 'Display the specified number of records, then stop'
complete -c pg_waldump -s p -d 'Specifies a directory to search for WAL segment files or a directory with a p…'
complete -c pg_waldump -o 'q
.br
--quiet' -d 'Do not print any output, except for errors'
complete -c pg_waldump -s r -d 'Only display records generated by the specified resource manager'
complete -c pg_waldump -s R -d 'Only display records that modify blocks in the given relation'
complete -c pg_waldump -s s -d 'WAL location at which to start reading'
complete -c pg_waldump -s t -d 'Timeline from which to read WAL records'
complete -c pg_waldump -o 'V
.br
--version' -d 'Print the pg_waldump version and exit'
complete -c pg_waldump -o 'w
.br
--fullpage' -d 'Only display records that include full page images'
complete -c pg_waldump -s x -d 'Only display records marked with the given transaction ID'
complete -c pg_waldump -o 'z
.br
--stats' -d 'Display summary statistics (number and size of records and full-page images) …'
complete -c pg_waldump -l save-fullpage -d 'Save full page images found in the WAL records to the save_path directory'
complete -c pg_waldump -o '?
.br
--help' -d 'Show help about pg_waldump command line arguments, and exit'
complete -c pg_waldump -s b
complete -c pg_waldump -l bkp-details
complete -c pg_waldump -l block
complete -c pg_waldump -l relation -d or
complete -c pg_waldump -l end
complete -c pg_waldump -s f
complete -c pg_waldump -l follow
complete -c pg_waldump -l fork
complete -c pg_waldump -l limit
complete -c pg_waldump -l path
complete -c pg_waldump -s q
complete -c pg_waldump -l quiet
complete -c pg_waldump -l rmgr
complete -c pg_waldump -l start
complete -c pg_waldump -l timeline
complete -c pg_waldump -s V
complete -c pg_waldump -l version
complete -c pg_waldump -s w
complete -c pg_waldump -l fullpage
complete -c pg_waldump -l xid
complete -c pg_waldump -s z
complete -c pg_waldump -l stats
complete -c pg_waldump -s '?'
complete -c pg_waldump -l help

