# pkgctl-diff
# Autogenerated from man page /usr/share/man/man1/pkgctl-diff.1.gz
complete -c pkgctl-diff -s M -l makepkg-config -d 'Set an alternate makepkg configuration file'
complete -c pkgctl-diff -s P -l pool -d 'Search diff target in pool dir (default \\*(Aq/srv/ftp/pool\\*(Aq)'
complete -c pkgctl-diff -s v -l verbose -d 'Provide more detailed/unfiltered output'
complete -c pkgctl-diff -s h -l help -d 'Show a help text'
complete -c pkgctl-diff -l color
complete -c pkgctl-diff -s u -s U -l unified
complete -c pkgctl-diff -s y -l side-by-side
complete -c pkgctl-diff -s W -l width
complete -c pkgctl-diff -s l -l list
complete -c pkgctl-diff -s d -l diffoscope
complete -c pkgctl-diff -s p -l pkginfo
complete -c pkgctl-diff -s b -l buildinfo

