# pkgctl-search
# Autogenerated from man page /usr/share/man/man1/pkgctl-search.1.gz
complete -c pkgctl-search -s h -l help -d 'Show a help text'
complete -c pkgctl-search -o banner -d '*       Partial        bug error 50* \\       Escape         \\*md #       Issu…'
complete -c pkgctl-search -l no-default-filter
complete -c pkgctl-search -l json
complete -c pkgctl-search -s F -l format
complete -c pkgctl-search -s N -l no-line-number

