# pkgctl-version-upgrade
# Autogenerated from man page /usr/share/man/man1/pkgctl-version-upgrade.1.gz
complete -c pkgctl-version-upgrade -s v -l verbose -d 'Display results including up-to-date versions'
complete -c pkgctl-version-upgrade -s h -l help -d 'Show a help text'

