# pkgctl-repo-clone
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-clone.1.gz
complete -c pkgctl-repo-clone -s m -l maintainer -d 'Clone all packages of the named maintainer'
complete -c pkgctl-repo-clone -l protocol -d 'Clone the repository over https'
complete -c pkgctl-repo-clone -l universe -d 'Clone all existing packages, useful for cache warming'
complete -c pkgctl-repo-clone -l switch -d 'Switch to a specified version'
complete -c pkgctl-repo-clone -s j -l jobs -d 'Run up to N jobs in parallel'
complete -c pkgctl-repo-clone -s h -l help -d 'Show a help text'

