# pkgctl-auth-login
# Autogenerated from man page /usr/share/man/man1/pkgctl-auth-login.1.gz
complete -c pkgctl-auth-login -s g -l gen-access-token -d 'Open the URL to generate a new personal access token'
complete -c pkgctl-auth-login -s h -l help -d 'Show a help text'

