# pkgctl-repo-configure
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-configure.1.gz
complete -c pkgctl-repo-configure -l protocol -d 'Configure remote url to use https'
complete -c pkgctl-repo-configure -s j -l jobs -d 'Run up to N jobs in parallel'
complete -c pkgctl-repo-configure -s h -l help -d 'Show a help text'

