# pkgctl-repo-web
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-web.1.gz
complete -c pkgctl-repo-web -l print -d 'Print the url instead of opening it with xdg-open'
complete -c pkgctl-repo-web -s h -l help -d 'Show a help text'

