# pkgctl-release
# Autogenerated from man page /usr/share/man/man1/pkgctl-release.1.gz
complete -c pkgctl-release -s m -l message -d 'Use the given <msg> as the commit message'
complete -c pkgctl-release -s r -l repo -d 'Specify target repository for new packages not in any official repo'
complete -c pkgctl-release -s s -l staging -d 'Build against the staging counterpart of the auto-detected repo'
complete -c pkgctl-release -s t -l testing -d 'Build against the testing counterpart of the auto-detected repo'
complete -c pkgctl-release -s u -l db-update -d 'Automatically update the pacman database after uploading'
complete -c pkgctl-release -s h -l help -d 'Show a help text'

