# pkgctl-repo-create
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-create.1.gz
complete -c pkgctl-repo-create -s c -l clone -d 'Clone the Git repository after creation'
complete -c pkgctl-repo-create -s h -l help -d 'Show a help text'

