# pkgctl-auth-status
# Autogenerated from man page /usr/share/man/man1/pkgctl-auth-status.1.gz
complete -c pkgctl-auth-status -s t -l show-token -d 'Display the auth token'
complete -c pkgctl-auth-status -s h -l help -d 'Show a help text'

