# pkgctl-build
# Autogenerated from man page /usr/share/man/man1/pkgctl-build.1.gz
complete -c pkgctl-build -s h -l help -d 'Show a help text'
complete -c pkgctl-build -l arch
complete -c pkgctl-build -l repo
complete -c pkgctl-build -s s -l staging
complete -c pkgctl-build -s t -l testing
complete -c pkgctl-build -s o -l offload
complete -c pkgctl-build -s c -l clean
complete -c pkgctl-build -l inspect
complete -c pkgctl-build -s w -l worker
complete -c pkgctl-build -l nocheck
complete -c pkgctl-build -s I -l install-to-chroot
complete -c pkgctl-build -s i -l install-to-host
complete -c pkgctl-build -l pkgver
complete -c pkgctl-build -l pkgrel
complete -c pkgctl-build -l rebuild
complete -c pkgctl-build -l update-checksums
complete -c pkgctl-build -s e -l edit
complete -c pkgctl-build -s r -l release
complete -c pkgctl-build -s m -l message
complete -c pkgctl-build -s u -l db-update

