# pkgctl-repo-switch
# Autogenerated from man page /usr/share/man/man1/pkgctl-repo-switch.1.gz
complete -c pkgctl-repo-switch -l discard-changes -d 'Proceed even if the index or the working tree differs from HEAD'
complete -c pkgctl-repo-switch -s f -l force -d 'An alias for --discard-changes'
complete -c pkgctl-repo-switch -s h -l help -d 'Show a help text'

