# pkgctl-db-remove
# Autogenerated from man page /usr/share/man/man1/pkgctl-db-remove.1.gz
complete -c pkgctl-db-remove -s a -l arch -d 'Override the architecture (disables auto-detection)'
complete -c pkgctl-db-remove -s h -l help -d 'Show a help text'

