# pkgctl-aur-drop-from-repo
# Autogenerated from man page /usr/share/man/man1/pkgctl-aur-drop-from-repo.1.gz
complete -c pkgctl-aur-drop-from-repo -l no-disown -d 'Do not disown the package on the AUR'
complete -c pkgctl-aur-drop-from-repo -s f -l force -d 'Force push to the AUR overwriting the remote repository'
complete -c pkgctl-aur-drop-from-repo -s h -l help -d 'Show a help text'

