# pkgctl-version-check
# Autogenerated from man page /usr/share/man/man1/pkgctl-version-check.1.gz
complete -c pkgctl-version-check -s v -l verbose -d 'Display results including up-to-date versions'
complete -c pkgctl-version-check -s h -l help -d 'Show a help text'

