# repo-overview
# Autogenerated from man page /usr/share/man/man1/repo-overview.1.gz
complete -c repo-overview -s h -l help -d 'show this help message and exit'
complete -c repo-overview -s c -l current-branch -d 'consider only checked out branches'
complete -c repo-overview -l no-current-branch -d 'consider all local branches . SS Logging options:'
complete -c repo-overview -s v -l verbose -d 'show all output'
complete -c repo-overview -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-overview -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-overview -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-overview -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-overview -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

