# repo-rebase
# Autogenerated from man page /usr/share/man/man1/repo-rebase.1.gz
complete -c repo-rebase -s h -l help -d 'show this help message and exit'
complete -c repo-rebase -l fail-fast -d 'stop rebasing after first error is hit'
complete -c repo-rebase -s f -l force-rebase -d 'pass --force-rebase to git rebase'
complete -c repo-rebase -l no-ff -d 'pass --no-ff to git rebase'
complete -c repo-rebase -l autosquash -d 'pass --autosquash to git rebase'
complete -c repo-rebase -l whitespace -d 'pass --whitespace to git rebase'
complete -c repo-rebase -l auto-stash -d 'stash local modifications before starting'
complete -c repo-rebase -s m -l onto-manifest -d 'rebase onto the manifest version instead of upstream HEAD (this helps to make…'
complete -c repo-rebase -s v -l verbose -d 'show all output'
complete -c repo-rebase -s q -l quiet -d 'only show errors'
complete -c repo-rebase -s i -l interactive -d 'interactive rebase (single project only) . SS Multi-manifest options:'
complete -c repo-rebase -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-rebase -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-rebase -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-rebase -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

