# repo-list
# Autogenerated from man page /usr/share/man/man1/repo-list.1.gz
complete -c repo-list -s h -l help -d 'show this help message and exit'
complete -c repo-list -s r -l regex -d 'filter the project list based on regex or wildcard matching of strings'
complete -c repo-list -s g -l groups -d 'filter the project list based on the groups the project is in'
complete -c repo-list -s a -l all -d 'show projects regardless of checkout state'
complete -c repo-list -s n -l name-only -d 'display only the name of the repository'
complete -c repo-list -s p -l path-only -d 'display only the path of the repository'
complete -c repo-list -s f -l fullpath -d 'display the full work tree path instead of the relative path'
complete -c repo-list -l relative-to -d 'display paths relative to this one (default: top of repo client checkout) '
complete -c repo-list -s v -l verbose -d 'show all output'
complete -c repo-list -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-list -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-list -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-list -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-list -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

