# repo-start
# Autogenerated from man page /usr/share/man/man1/repo-start.1.gz
complete -c repo-start -s h -l help -d 'show this help message and exit'
complete -c repo-start -s j -l jobs -d 'number of jobs to run in parallel (default: based on number of CPU cores)'
complete -c repo-start -l all -d 'begin branch in all projects'
complete -c repo-start -s r -l rev -l revision -d 'point branch at this revision instead of upstream'
complete -c repo-start -l head -l HEAD -d 'abbreviation for --rev HEAD . SS Logging options:'
complete -c repo-start -s v -l verbose -d 'show all output'
complete -c repo-start -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-start -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-start -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-start -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-start -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

