# repo
# Autogenerated from man page /usr/share/man/man1/repo.1.gz
complete -c repo -s h -l help -d 'show this help message and exit'
complete -c repo -l help-all -d 'show this help message with all subcommands and exit'
complete -c repo -s p -l paginate -d 'display command output in the pager'
complete -c repo -l no-pager -d 'disable the pager'
complete -c repo -l color -d 'control color usage: auto, always, never'
complete -c repo -l trace -d 'trace git command execution (REPO_TRACE=1)'
complete -c repo -l trace-to-stderr -d 'trace outputs go to stderr in addition to . repo/TRACE_FILE'
complete -c repo -l trace-python -d 'trace python command execution'
complete -c repo -l time -d 'time repo command execution'
complete -c repo -l version -d 'display this version of repo'
complete -c repo -l show-toplevel -d 'display the path of the top-level directory of the repo client checkout'
complete -c repo -l event-log -d 'filename of event log to append timeline to'
complete -c repo -l git-trace2-event-log -d 'directory to write git trace2 event log to'
complete -c repo -l submanifest-path -d 'submanifest path . SS "The complete list of recognized repo commands is:"'

