# repo-prune
# Autogenerated from man page /usr/share/man/man1/repo-prune.1.gz
complete -c repo-prune -s h -l help -d 'show this help message and exit'
complete -c repo-prune -s j -l jobs -d 'number of jobs to run in parallel (default: based on number of CPU cores) '
complete -c repo-prune -s v -l verbose -d 'show all output'
complete -c repo-prune -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-prune -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-prune -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-prune -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-prune -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

