# repo-status
# Autogenerated from man page /usr/share/man/man1/repo-status.1.gz
complete -c repo-status -s h -l help -d 'show this help message and exit'
complete -c repo-status -s j -l jobs -d 'number of jobs to run in parallel (default: based on number of CPU cores)'
complete -c repo-status -s o -l orphans -d 'include objects in working directory outside of repo projects '
complete -c repo-status -s v -l verbose -d 'show all output'
complete -c repo-status -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-status -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-status -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-status -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-status -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'
complete -c repo-status -s m -d 'subcmds/status. py'

