# repo-selfupdate
# Autogenerated from man page /usr/share/man/man1/repo-selfupdate.1.gz
complete -c repo-selfupdate -s h -l help -d 'show this help message and exit . SS Logging options:'
complete -c repo-selfupdate -s v -l verbose -d 'show all output'
complete -c repo-selfupdate -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-selfupdate -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-selfupdate -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-selfupdate -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-selfupdate -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests . SS repo Version options:'
complete -c repo-selfupdate -l no-repo-verify -d 'do not verify repo source code'

