# repo-help
# Autogenerated from man page /usr/share/man/man1/repo-help.1.gz
complete -c repo-help -s h -l help -d 'show this help message and exit'
complete -c repo-help -s a -l all -d 'show the complete list of commands'
complete -c repo-help -l help-all -d 'show the --help of all commands . SS Logging options:'
complete -c repo-help -s v -l verbose -d 'show all output'
complete -c repo-help -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-help -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-help -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-help -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-help -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

