# repo-manifest
# Autogenerated from man page /usr/share/man/man1/repo-manifest.1.gz
complete -c repo-manifest -s h -l help -d 'show this help message and exit'
complete -c repo-manifest -s r -l revision-as-HEAD -d 'save revisions as current HEAD'
complete -c repo-manifest -s m -l manifest-name -d 'temporary manifest to use for this sync'
complete -c repo-manifest -l suppress-upstream-revision -d 'if in -r mode, do not write the upstream field (only of use if the branch nam…'
complete -c repo-manifest -l suppress-dest-branch -d 'if in -r mode, do not write the dest-branch field (only of use if the branch …'
complete -c repo-manifest -l json -d 'output manifest in JSON format (experimental)'
complete -c repo-manifest -l pretty -d 'format output for humans to read'
complete -c repo-manifest -l no-local-manifests -d 'ignore local manifests'
complete -c repo-manifest -s o -l output-file -o '\\/' -d 'file to save the manifest to.  (Filename prefix for multi-tree. ) '
complete -c repo-manifest -s v -l verbose -d 'show all output'
complete -c repo-manifest -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-manifest -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-manifest -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-manifest -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-manifest -s / -d 'file to save the manifest to.  (Filename prefix for multi-tree'
complete -c repo-manifest -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'
complete -c repo-manifest -l depth

