# repo-abandon
# Autogenerated from man page /usr/share/man/man1/repo-abandon.1.gz
complete -c repo-abandon -s h -l help -d 'show this help message and exit'
complete -c repo-abandon -s j -l jobs -d 'number of jobs to run in parallel (default: based on number of CPU cores)'
complete -c repo-abandon -l all -d 'delete all branches in all projects . SS Logging options:'
complete -c repo-abandon -s v -l verbose -d 'show all output'
complete -c repo-abandon -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-abandon -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-abandon -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-abandon -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-abandon -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

