# repo-forall
# Autogenerated from man page /usr/share/man/man1/repo-forall.1.gz
complete -c repo-forall -s h -l help -d 'show this help message and exit'
complete -c repo-forall -s j -l jobs -d 'number of jobs to run in parallel (default: based on number of CPU cores)'
complete -c repo-forall -s r -l regex -d 'execute the command only on projects matching regex or wildcard expression'
complete -c repo-forall -s i -l inverse-regex -d 'execute the command only on projects not matching regex or wildcard expression'
complete -c repo-forall -s g -l groups -d 'execute the command only on projects matching the specified groups'
complete -c repo-forall -s c -l command -d 'command (and arguments) to execute'
complete -c repo-forall -s e -l abort-on-errors -d 'abort if a command exits unsuccessfully'
complete -c repo-forall -l ignore-missing -d 'silently skip & do not exit non-zero due missing checkouts'
complete -c repo-forall -l interactive -d 'force interactive usage . SS Logging options:'
complete -c repo-forall -s v -l verbose -d 'show all output'
complete -c repo-forall -s q -l quiet -d 'only show errors'
complete -c repo-forall -s p -d 'show project headers before output . SS Multi-manifest options:'
complete -c repo-forall -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-forall -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-forall -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-forall -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

