# repo-stage
# Autogenerated from man page /usr/share/man/man1/repo-stage.1.gz
complete -c repo-stage -s h -l help -d 'show this help message and exit . SS Logging options:'
complete -c repo-stage -s v -l verbose -d 'show all output'
complete -c repo-stage -s q -l quiet -d 'only show errors'
complete -c repo-stage -s i -l interactive -d 'use interactive staging . SS Multi-manifest options:'
complete -c repo-stage -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-stage -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-stage -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-stage -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

