# repo-version
# Autogenerated from man page /usr/share/man/man1/repo-version.1.gz
complete -c repo-version -s h -l help -d 'show this help message and exit . SS Logging options:'
complete -c repo-version -s v -l verbose -d 'show all output'
complete -c repo-version -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-version -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-version -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-version -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-version -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

