# repo-download
# Autogenerated from man page /usr/share/man/man1/repo-download.1.gz
complete -c repo-download -s h -l help -d 'show this help message and exit'
complete -c repo-download -s b -l branch -d 'create a new branch first'
complete -c repo-download -s c -l cherry-pick -d 'cherry-pick instead of checkout'
complete -c repo-download -s x -l record-origin -d 'pass -x when cherry-picking'
complete -c repo-download -s r -l revert -d 'revert instead of checkout'
complete -c repo-download -s f -l ff-only -d 'force fast-forward merge . SS Logging options:'
complete -c repo-download -s v -l verbose -d 'show all output'
complete -c repo-download -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-download -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-download -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-download -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-download -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

