# repo-gitc-delete
# Autogenerated from man page /usr/share/man/man1/repo-gitc-delete.1.gz
complete -c repo-gitc-delete -s h -l help -d 'show this help message and exit'
complete -c repo-gitc-delete -s f -l force -d 'force the deletion (no prompt) . SS Logging options:'
complete -c repo-gitc-delete -s v -l verbose -d 'show all output'
complete -c repo-gitc-delete -s q -l quiet -d 'only show errors . SS Multi-manifest options:'
complete -c repo-gitc-delete -l outer-manifest -d 'operate starting at the outermost manifest'
complete -c repo-gitc-delete -l no-outer-manifest -d 'do not operate on outer manifests'
complete -c repo-gitc-delete -l this-manifest-only -d 'only operate on this (sub)manifest'
complete -c repo-gitc-delete -l no-this-manifest-only -l all-manifests -d 'operate on this manifest and its submanifests'

