# sogrep
# Autogenerated from man page /usr/share/man/man1/sogrep.1.gz
complete -c sogrep -s v -l verbose -d 'Provide detailed output containing the matched links for each package, the re…'
complete -c sogrep -s r -l refresh -d 'Refresh the links databases'
complete -c sogrep -s h -l help -d 'Show a help text'

