# tpm2_tr_encode
# Autogenerated from man page /usr/share/man/man1/tpm2_tr_encode.1.gz
complete -c tpm2_tr_encode -s c -l object-context -d 'Persistent handle'
complete -c tpm2_tr_encode -s f -l format -d 'Format selection for the public key output file'
complete -c tpm2_tr_encode -s o -l output -d 'The output file path, recording the serialized ESYS_TR'
complete -c tpm2_tr_encode -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tpm2_tr_encode -s v -l version -d 'tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_tr_encode -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_tr_encode -s Q -l quiet -d '[bu] 2'
complete -c tpm2_tr_encode -s Z -l enable-errata -d 'errata fixups'

