# tpm2_certifyX509certutil
# Autogenerated from man page /usr/share/man/man1/tpm2_certifyX509certutil.1.gz
complete -c tpm2_certifyX509certutil -s o -l outcert -d 'where the certificate will be written to.  The default is partial_cert'
complete -c tpm2_certifyX509certutil -s d -l days -d 'certificate will be valid starting from today'
complete -c tpm2_certifyX509certutil -s i -l issuer -d 'the cert in the following format: [en]issuer=[lq]C=US;O=org;OU=Org unit;CN=cn…'
complete -c tpm2_certifyX509certutil -s s -l subject -d 'cert in the following format: [en]subject=[lq]C=US;O=org;OU=Org unit;CN=cname…'
complete -c tpm2_certifyX509certutil -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tpm2_certifyX509certutil -s v -l version -d 'tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_certifyX509certutil -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_certifyX509certutil -s Q -l quiet -d '[bu] 2'
complete -c tpm2_certifyX509certutil -s Z -l enable-errata -d 'errata fixups'

