# tpm2_print
# Autogenerated from man page /usr/share/man/man1/tpm2_print.1.gz
complete -c tpm2_print -s t -l type -d 'Required.  Type of data structure'
complete -c tpm2_print -s f -l format -d 'Format selection for the public key output file'
complete -c tpm2_print -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tpm2_print -s v -l version -d 'tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_print -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_print -s Q -l quiet -d '[bu] 2'
complete -c tpm2_print -s Z -l enable-errata -d 'errata fixups'

