# tss2_pcrextend
# Autogenerated from man page /usr/share/man/man1/tss2_pcrextend.1.gz
complete -c tss2_pcrextend -s x -l pcr
complete -c tss2_pcrextend -s i -l data -d 'stdin): The event data to be extended'
complete -c tss2_pcrextend -s l -l logData -d 'stdin): Contains a JSON representation of data to be written to the PCR[cq]s …'
complete -c tss2_pcrextend -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_pcrextend -s v -l version -d 'tool, supported tctis and exit.  EXAMPLE tss2_pcrextend --pcr=16 --data=data'

