# tss2_encrypt
# Autogenerated from man page /usr/share/man/man1/tss2_encrypt.1.gz
complete -c tss2_encrypt -s p -l keyPath -d 'Identifies the encryption key'
complete -c tss2_encrypt -s f -l force -d 'Force overwriting the output file'
complete -c tss2_encrypt -s i -l plainText -d '(for stdin): The data to be encrypted'
complete -c tss2_encrypt -s o -l cipherText -d '(for stdout): Returns the JSON-encoded ciphertext'
complete -c tss2_encrypt -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_encrypt -s v -l version -d 'tool, supported tctis and exit'

