# tss2_authorizepolicy
# Autogenerated from man page /usr/share/man/man1/tss2_authorizepolicy.1.gz
complete -c tss2_authorizepolicy -s P -l policyPath -d 'policy.  A policyPath is composed of two elements, separated by [lq]/[rq]'
complete -c tss2_authorizepolicy -s p -l keyPath -d 'key.  [bu] 2'
complete -c tss2_authorizepolicy -s r -l policyRef -d '(for stdin): A byte buffer to be included in the signature'
complete -c tss2_authorizepolicy -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_authorizepolicy -s v -l version -d 'tool, supported tctis and exit'

