# tss2_changeauth
# Autogenerated from man page /usr/share/man/man1/tss2_changeauth.1.gz
complete -c tss2_changeauth -s a -l authValue -d 'The new UTF-8 password.  Optional parameter'
complete -c tss2_changeauth -s p -l entityPath -d 'The path identifying the entity to modify'
complete -c tss2_changeauth -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_changeauth -s v -l version -d 'tool, supported tctis and exit'

