# tss2_quote
# Autogenerated from man page /usr/share/man/man1/tss2_quote.1.gz
complete -c tss2_quote -s x -l pcrList -d 'An array holding the PCR indices to quote against'
complete -c tss2_quote -s Q -l qualifyingData
complete -c tss2_quote -s l -l pcrLog -d 'stdout): Returns the PCR log for the chosen PCR.  Optional parameter'
complete -c tss2_quote -s f -l force -d 'Force overwriting the output file'
complete -c tss2_quote -s p -l keyPath -d 'Identifies the signing key'
complete -c tss2_quote -s q -l quoteInfo -d '(for stdout): Returns a JSON-encoded structure holding the inputs to the quot…'
complete -c tss2_quote -s o -l signature -d '(for stdout): Returns the signature over the quoted material'
complete -c tss2_quote -s c -l certificate -d '(for stdout): The certificate associated with keyPath in PEM format'
complete -c tss2_quote -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_quote -s v -l version -d 'tool, supported tctis and exit'

