# tss2_setcertificate
# Autogenerated from man page /usr/share/man/man1/tss2_setcertificate.1.gz
complete -c tss2_setcertificate -s p -l path -d 'Identifies the entity to be associated with the certificate'
complete -c tss2_setcertificate -s i -l x509certData -d '(for stdin): The PEM encoded certificate.  Optional parameter'
complete -c tss2_setcertificate -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_setcertificate -s v -l version -d 'tool, supported tctis and exit'

