# tss2_getcertificate
# Autogenerated from man page /usr/share/man/man1/tss2_getcertificate.1.gz
complete -c tss2_getcertificate -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getcertificate -s p -l path -d 'The entity whose certificate is requested'
complete -c tss2_getcertificate -s o -l x509certData -d '(for stdout): Returns the PEM encoded certificate'
complete -c tss2_getcertificate -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_getcertificate -s v -l version -d 'tool, supported tctis and exit'

