# tss2_verifysignature
# Autogenerated from man page /usr/share/man/man1/tss2_verifysignature.1.gz
complete -c tss2_verifysignature -s d -l digest -d 'stdin): The data that was signed, already hashed according to the cryptograph…'
complete -c tss2_verifysignature -s p -l keyPath -d 'Path to the verification public key'
complete -c tss2_verifysignature -s i -l signature -d '(for stdin): The signature to be verified'
complete -c tss2_verifysignature -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_verifysignature -s v -l version -d 'tool, supported tctis and exit'

