# tss2_sign
# Autogenerated from man page /usr/share/man/man1/tss2_sign.1.gz
complete -c tss2_sign -s p -l keyPath -d 'The path to the signing key'
complete -c tss2_sign -s s -l padding -d 'The padding scheme used'
complete -c tss2_sign -s c -l certificate -d '(for stdout): The certificate associated with keyPath in PEM format'
complete -c tss2_sign -s d -l digest -d 'stdin): The data to be signed, already hashed'
complete -c tss2_sign -s f -l force -d 'Force overwriting the output file'
complete -c tss2_sign -s k -l publicKey -d '(for stdout): The public key associated with keyPath in PEM format'
complete -c tss2_sign -s o -l signature -d '(for stdout): Returns the signature in binary form'
complete -c tss2_sign -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_sign -s v -l version -d 'tool, supported tctis and exit'

