# tss2_import
# Autogenerated from man page /usr/share/man/man1/tss2_import.1.gz
complete -c tss2_import -s p -l path -d 'The path of the new object'
complete -c tss2_import -s i -l importData -d '(for stdin): The data to be imported'
complete -c tss2_import -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_import -s v -l version -d 'tool, supported tctis and exit'

