# tss2_getplatformcertificates
# Autogenerated from man page /usr/share/man/man1/tss2_getplatformcertificates.1.gz
complete -c tss2_getplatformcertificates -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getplatformcertificates -s o -l certificates -d '(for stdout): Returns a continuous buffer containing the concatenated platfor…'
complete -c tss2_getplatformcertificates -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_getplatformcertificates -s v -l version -d 'tool, supported tctis and exit'

