# tss2_decrypt
# Autogenerated from man page /usr/share/man/man1/tss2_decrypt.1.gz
complete -c tss2_decrypt -s p -l keyPath -d 'Identifies the decryption key'
complete -c tss2_decrypt -s i -l cipherText -d '(for stdin): The JSON-encoded cipherText'
complete -c tss2_decrypt -s f -l force -d 'Force Overwriting the output file'
complete -c tss2_decrypt -s o -l plainText -d '(for stdout): Returns the decrypted data.  Optional parameter'
complete -c tss2_decrypt -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_decrypt -s v -l version -d 'tool, supported tctis and exit'

