# tss2_gettpmblobs
# Autogenerated from man page /usr/share/man/man1/tss2_gettpmblobs.1.gz
complete -c tss2_gettpmblobs -s f -l force -d 'Force overwriting the output file'
complete -c tss2_gettpmblobs -s p -l path -d 'The path of the object for which the blobs will be returned'
complete -c tss2_gettpmblobs -s u -l tpm2bPublic -d '(for stdout): The returned public area of the object as a marshalled TPM2B_PU…'
complete -c tss2_gettpmblobs -s r -l tpm2bPrivate -d '(for stdout): The returned private area of the object as a marshalled TPM2B_P…'
complete -c tss2_gettpmblobs -s l -l policy -d 'stdout): The returned policy associated with the object, encoded in JSON'
complete -c tss2_gettpmblobs -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_gettpmblobs -s v -l version -d 'tool, supported tctis and exit'

