# tss2_nvextend
# Autogenerated from man page /usr/share/man/man1/tss2_nvextend.1.gz
complete -c tss2_nvextend -s i -l data -d 'stdin): The data to be extended into the NV space'
complete -c tss2_nvextend -s p -l nvPath -d 'Identifies the NV space to write'
complete -c tss2_nvextend -s l -l logData -d 'stdin): A JSON representation of data to be written to the PCR[cq]s event log'
complete -c tss2_nvextend -s h -l help -d 'By default, it attempts to invoke the manpager for the tool, however, on fail…'
complete -c tss2_nvextend -s v -l version -d 'tool, supported tctis and exit'

