# wavemon
# Autogenerated from man page /usr/share/man/man1/wavemon.1.gz
complete -c wavemon -s i -d 'override autodetection and use the specified interface'
complete -c wavemon -s g -d 'check screen geometry: a minimum size is required for proper display; this fl…'
complete -c wavemon -s h -d 'print help and exit'

