# xlsx2csv
# Autogenerated from man page /usr/share/man/man1/xlsx2csv.1.gz
complete -c xlsx2csv -s d -l delimiter -d 'X Item "-d DELIMITER, --delimiter=DELIMITER" Output csv columns delimiter'
complete -c xlsx2csv -s f -l dateformat -d 'X Item "-f DATEFORMAT, --dateformat=DATEFORMAT" Set date/time format'
complete -c xlsx2csv -s i -l ignoreempty -d 'X Item "-i, --ignoreempty" Skip empty lines'
complete -c xlsx2csv -s p -l sheetdelimiter -d 'X Item "-p SHEETDELIMITER, --sheetdelimiter=SHEETDELIMITER" Sheet delimiter u…'
complete -c xlsx2csv -s q -l quoting -d 'X Item "-q QUOTING, --quoting=QUOTING" Output csv fields quoting'
complete -c xlsx2csv -s r -l recursive -d 'X Item "-r, --recursive" Convert recursively'
complete -c xlsx2csv -s s -l sheet -d 'X Item "-s SHEETID, --sheet=SHEETID" Sheet to convert (0 for all sheets)'
complete -c xlsx2csv -s h -l help -d 'X Item "-h, --help" Display short help and exit'
complete -c xlsx2csv -l version

