export QT_QPA_PLATFORMTHEME=qt5ct
export MOZ_USE_XINPUT2=1
# export GDK_DPI_SCALE=1
export GTK_USE_PORTAL=1
export GLFW_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT4_IM_MODULE=fcitx
export CLUTTER_IM_MODULE=fcitx
# export INPUT_METHOD=ibus
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:/usr/lib/safe-rm:$PATH:$HOME/bin:$HOME/.bun/bin:$HOME/.local/bin:$HOME/.cargo/bin:$GEM_HOME/bin:$HOME/.local/share/neovim/bin:$HOME/.local/share/bob/nvim-bin:$HOME/.pyenv/bin:$HOME/android_root/platform-tools/adb:/opt/cuda/bin:/usr/local/VideoSubFinder:$HOME/.yarn/bin:$HOME/go/bin:$HOME/.dotnet/tools"
export npm_config_prefix="$HOME/.local"
export JAVA_HOME="$(java-config -O)"
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=kitty
# export TERM=xterm-kitty
export COLORTERM=truecolor
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export CCACHE_MAXSIZE=50G # 50 GB
export CUDAToolkit_ROOT=/opt/cuda
export GPG_TTY=$(tty)

export XCURSOR_SIZE=24
export MOZ_ENABLE_WAYLAND=1
export OZONE_PLATFORM=wayland
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export GDK_DEBUG=portals
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export WLR_DRM_DEVICES=/dev/dri/amd-igpu:/dev/dri/nvidia-egpu
export WLR_RENDERER=vulkan
# export ENABLE_HDR_WSI=1
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
# Manually export the most common ones
export XDG_DESKTOP_DIR="$(xdg-user-dir DESKTOP)"
export XDG_DOWNLOAD_DIR="$(xdg-user-dir DOWNLOAD)"
export XDG_TEMPLATES_DIR="$(xdg-user-dir TEMPLATES)"
export XDG_PUBLICSHARE_DIR="$(xdg-user-dir PUBLICSHARE)"
export XDG_DOCUMENTS_DIR="$(xdg-user-dir DOCUMENTS)"
export XDG_MUSIC_DIR="$(xdg-user-dir MUSIC)"
export XDG_PICTURES_DIR="$(xdg-user-dir PICTURES)"
export XDG_VIDEOS_DIR="$(xdg-user-dir VIDEOS)"
export XDG_CONFIG_HOME="$(xdg-user-dir CONFIG_HOME)"
unset SSH_AGENT_PID
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
export MPD_HOST=$HOME/.config/mpd/socket
