#!/usr/bin/env bash

# Only do power management if PreserveVideoMemoryAllocations is enabled.
grep -q "NVreg_PreserveVideoMemoryAllocations=1" /etc/modprobe.d/nvidia.conf || exit 0

case $1 in
pre)
  /usr/bin/logger -t suspend -s "NVIDIA: Suspending..."
  case $2 in
  hibernate) /usr/bin/nvidia-sleep.sh "hibernate" ;;
  **) /usr/bin/nvidia-sleep.sh "suspend" ;;
  esac
  /usr/bin/logger -t suspend -s "NVIDIA: Done suspending, carry on."
  ;;
post)
  /usr/bin/logger -t suspend -s "NVIDIA: Resuming..."
  /usr/bin/nvidia-sleep.sh "resume"
  /usr/bin/logger -t suspend -s "NVIDIA: Done resuming."
  ;;
**) ;;
esac
