# Execute your favorite apps at launch
exec-once = shikane --config ~/.config/shikane/config_hyprland.toml
exec-once = ~/.config/hypr/scripts/disable-touchpad-startup.sh
exec-once = waybar --config ~/.config/waybar/config_hypr --style ~/.config/waybar/style_hypr.css
exec-once = hyprpm reload -n
exec-once = wl-paste --watch cliphist store
# exec-once = hyprctl setcursor Qogir-cursors 24
exec-once = gsettings set org.gnome.desktop.interface font-name 'Hack Nerd Font 16'
exec-once = dbus-update-activation-environment --all
exec-once = ~/.config/hypr/scripts/xdg-portal-hyprland.sh
exec-once = /usr/libexec/hyprpolkitagent
exec-once = hyprpaper
exec-once = dex -a
exec-once = export $(gnome-keyring-daemon)
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/local/libexec/file_manager_dbus
exec-once = gpgconf --launch gpg-agent
exec-once = ~/.config/sway/scripts/battery-watch.sh
exec-once = mpd --no-daemon ~/.config/mpd/mpd.conf
exec-once = mpd-mpris -network unix  --host ~/.config/mpd/socket
exec-once = hypridle -q

# exec-once = waypaper-engine daemon
# exec-once = ibus start --type wayland
# exec-once = socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock EXEC:"shellevents ~/.config/ibus-bamboo/sway-watch-window-change.sh",nofork
