# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor = , preferred, auto, auto
# monitor = eDP-1,preferred,auto,auto,bitdepth, 10, cm, dcip3
monitorv2 {
  output = eDP-1
  mode = 2560x1600@240
  scale = 1.33
  position = auto-right
  bitdepth = 8
  vrr = 1
  icc = /home/huyhoang/.config/sway/scripts/color_profiles/TPLCD_2039_Default.icm
}

monitorv2 {
  output = DP-1
  mode = 2560x1440@240
  position = 0x0
  scale = 1
  bitdepth = 8
  vrr = 1
  cm = auto
  icc = /home/huyhoang/.config/sway/scripts/color_profiles/Q27G42ZE.icm
}

monitorv2 {
  output = HDMI-A-1
  mode = 640x480@59.94Hz
  position = 0x4920
}

render {
}
