# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor = , preferred, auto, auto
# monitor = eDP-1,preferred,auto,auto,bitdepth, 10, cm, dcip3
monitorv2 {
  output = eDP-1
  mode = highrr
  position = auto
  scale = 1.33
  bitdepth = 10
  vrr = 1
  cm = auto
  # sdrbrightness = 1
  # sdrsaturation = 1
  # #
  # # # HDR static metadata (from CTA-861)
  # min_luminance = 0        # EDID 'Desired content min luminance'
  # max_luminance = 497      # EDID 'Desired content max luminance' (MaxCLL)
  # max_avg_luminance = 497  # EDID 'Desired content max frame-average luminance' (MaxFALL)
  # #
  # # # SDR tonemap guidance (from DisplayID Brightness Luminance Range)
  # sdr_min_luminance = 0
  # sdr_max_luminance = 500

  # Capability flags (from EDID colorimetry / EOTF)
  supports_wide_color = 0
  supports_hdr = 0
}
render {
  direct_scanout = 0
  cm_fs_passthrough = 1
  cm_auto_hdr = 2
}
