## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

# Use non-default path for file preview script?
# ranger ships with scope.sh, a script that calls external programs (see
# README.md for dependencies) to preview images, archives, etc.
set preview_script ~/.config/ranger/scope.sh
set line_numbers relative
# Use the external preview script or display simple plain text or image previews?
set use_preview_script true

# Be aware of version control systems and display information.
set vcs_aware false

# Use one of the supported image preview protocols
set preview_images true

set preview_images_method ueberzug
# Use a unicode "..." character to mark cut-off filenames?
set unicode_ellipsis true

# Which colorscheme to use?  These colorschemes are available by default:
# default, jungle, snow, solarized
set colorscheme norddark

# Draw the status bar on top of the browser window (default: bottom)
set status_bar_on_top false

# Draw borders around columns?
set draw_borders true

# Display the directory name in tabs?
set dirname_in_tabs true 

# Enable this if key combinations with the Alt Key don't work for you.
# (Especially on xterm)
set xterm_alt_key false

# Use fuzzy tab completion with the "cd" command. For example,
# ":cd /u/lo/b<tab>" expands to ":cd /usr/local/bin".
set cd_tab_fuzzy true

# Save tabs on exit
set save_tabs_on_exit true

# Enable scroll wrapping - moving down while on the last item will wrap around to
# the top and vice versa.
set wrap_scroll true

# Column ratio
set column_ratios 1,3,4

# Hidden filter
set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$

# ===================================================================
# == Local Options
# ===================================================================
setlocal path=~/Downloads sort mtime
setlocal path=/mnt/remote preview_directories false
setlocal path=/mnt/remote preview_files false
setlocal path=/mnt/remote preview_images false
setlocal path=/mnt/remote collapse_preview true

# trash lives in ~/.local/share/Trash/files
map gt cd ~/.local/share/Trash/files
map / console filter%space
# Trash instead of permanently delete
# map dD shell -d trash-put %s
set show_hidden false
# create new tab with ctrl + n
map <c-n>  eval fm.tab_new('%d')
# filter find in same folder
map f console scout -ftse%space
map r chain draw_possible_programs; console -p10 open_with%space
# mount
map ma eval fm.mount_android()
map mua eval fm.unmount_android()
# https://github.com/ranger/ranger/issues/456
eval import os.path as fs; fm.fs=fs; fm.avfsdir=fs.join(os.getenv('XDG_RUNTIME_DIR', f'/run/user/{os.getuid()}'), 'avfs')
eval cmd(f'setlocal path={fm.avfsdir} preview_files false')  # WARN: fragile, no escaping on expansion
map h eval (lambda x: fm.select_file(x.removeprefix(fm.avfsdir)) if (x.startswith(fm.avfsdir) and fm.fs.isfile(x)) else fm.move(left=1))(fm.thisdir.path.removesuffix('#'))
map l eval (lambda x, z: (fm.select_file(f'{z}'), fm.cd(f'{z}#/')) if (x.is_file and (x.container or x.extension in ['zst', 'zstd', 'lz'])) else fm.move(right=1))(fm.thisfile, fm.avfsdir + fm.thisfile.path.removeprefix(fm.avfsdir))
