profile=high-quality

# ==========================================================================
# General Playback & Video Output
# ==========================================================================
save-position-on-quit=yes
save-watch-history=yes
write-filename-in-watch-later-config=yes
watch-later-options-remove=sub-pos
# vo=gpu-next
# gpu-api=vulkan
# gpu-context=waylandvk
# Use 'auto' to intelligently select the best hardware decoder.
# On your system, this will default to 'qsv'. This is more robust.
hwdec=auto
osc=no
# for HDR
# dither-depth=10
# target-colorspace-hint=yes
# hdr-compute-peak=yes

# ==========================================================================
# Subtitles & Audio
# ==========================================================================
audio-device=auto
# Audio passthrough DTS (và Dolby)
audio-spdif=ac3,eac3,dts,dts-hd,truehd
# Only mpv can play audio, other apps can't
audio-exclusive=yes
audio-channels=auto

slang=vn,vie
alang=jpn,jp,eng,en,enUS,en-US,de,ger
sub-auto=fuzzy
embeddedfonts=yes
blend-subtitles=no

# Keep for compatibility with older subtitle formats
sub-ass-use-video-data=all
sub-ass-scale-with-window=no

# Personal preference, 1 is a good default
sub-border-size=1

# Auto-load external audio files with similar names
audio-file-auto=fuzzy

sub-font="UVN Sach Vo"
# sub-font-size=36
sub-bold=yes
# ==========================================================================
# OSD & Window
# ==========================================================================
osd-playing-msg='${media-title}'
autofit=85%x85%

# ==========================================================================
# Caching (More Reasonable Values)
# ==========================================================================
# These settings provide good buffering without excessive RAM usage.
cache=yes
demuxer-max-bytes=350MiB
demuxer-readahead-secs=200

[protocol.http]
profile=protocol-network

[protocol.https]
profile=protocol-network

[protocol-network]
hls-bitrate=max
# Use the general cache settings defined above.
